# Generated by Django 5.0.6 on 2024-07-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('mailing_address', models.CharField(max_length=200)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('children_names_ages', models.TextField(blank=True, null=True)),
                ('membership_status', models.CharField(choices=[('N', 'New member'), ('E', 'Existing member'), ('V', 'Visitor')], max_length=1)),
                ('date_of_membership', models.DateField()),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('baptism_place', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_church', models.CharField(blank=True, max_length=100, null=True)),
                ('ministry_interests', models.TextField(blank=True, null=True)),
                ('spiritual_gifts_talents', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('emergency_contact_phone_number', models.CharField(max_length=15)),
                ('special_needs_allergies', models.TextField(blank=True, null=True)),
                ('preferred_service_time', models.CharField(blank=True, max_length=50, null=True)),
                ('comments_notes', models.TextField(blank=True, null=True)),
                ('photo_consent', models.BooleanField(default=False)),
                ('privacy_consent', models.BooleanField(default=False)),
            ],
        ),
    ]
